# Generated by Django 5.2.14 on 2026-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
