# Generated by Django 5.2.14 on 2026-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoproject_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='engine',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMUNITY', 'Community')], default='PREMIUM', max_length=20),
        ),
    ]
