# Generated by Django 5.2.14 on 2026-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoproject_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='slides',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
