# Generated by Django 5.2.14 on 2026-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videoproject_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='engine',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMUNITY', 'Community')], default='COMMUNITY', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='voice',
            field=models.CharField(default='bark_v2', max_length=50),
        ),
    ]
